# Generated by Django 5.1.1 on 2024-09-23 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLoja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='appLoja.categoria'),
            preserve_default=False,
        ),
    ]
