# Generated by Django 5.1.1 on 2024-09-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLoja', '0002_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
