# Generated by Django 5.1.1 on 2024-09-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLoja', '0003_alter_venda_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.IntegerField(default=0),
        ),
    ]
